web/router.ex
defmodule Academy.Router do
  use Academy.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers,
      %{"Content-Security-Policy"
       => ~S(
          default-src 'none';
          script-src 'self' 'unsafe-inline';
          connect-src 'self';
          img-src 'self';
          font-src 'self';
          style-src 'self';
        )}
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Academy do
    pipe_through [:browser, :browser_auth]

    get "/",      UserController, :index
    get "/about", PageController, :about

    get  "/login", SessionController, :new
    post "/login", SessionController, :create

    get "/logout", SessionController, :delete

    resources "/users", UserController, only: [:index, :show]

    get      "/account",      UserController, :show_self
    get      "/account/edit", UserController, :edit
    patch    "/account/edit", UserController, :update
    put      "/account/edit", UserController, :update
    delete   "/account/edit", UserController, :delete

    get  "/account/skills/edit", SkillLevelController, :edit
    post "/account/skills",      SkillLevelController, :update

    resources "/skills",          SkillController, except: [:show, :update, :create]
    post      "/skills/new",      SkillController, :create
    patch     "/skills/:id/edit", SkillController, :update
    put       "/skills/:id/edit", SkillController, :update

    resources "/skill_categories",          SkillCategoryController, only: [:edit, :new, :delete]
    post      "/skill_categories/new",      SkillCategoryController, :create
    patch     "/skill_categories/:id/edit", SkillCategoryController, :update
    put       "/skill_categories/:id/edit", SkillCategoryController, :update

    get  "/mail/:user", MailController, :new
    post "/mail/:user", MailController, :send
  end

  scope "/api", Academy do
    pipe_through :api

    resources "/users", API.UserController, only: [:index, :show]

    resources "/skills", API.SkillController, only: [:index, :show]

    resources "/skill_categories", API.SkillCategoryController, only: [:index, :show]
  end
end

web/models/skill.ex
defmodule Academy.Skill do
  @moduledoc ~S"""
  Defines a skill model.

  Composition
  -----------

  A skill is composed of a name, a description and an association with
  `Academy.SkillCategory`

  For getting the associations, see `Academy.User`.
  """

  use Academy.Web, :model

  schema "skills" do
    field :name, :string
    field :description, :string

    belongs_to :category, Academy.SkillCategory, on_replace: :nilify

    timestamps
  end

  @required_fields ~w(name description)a
  @optional_fields ~w()
  @fields @required_fields ++ @optional_fields

  @doc """
  Creates a changeset based on the `model` and `params`.

  For examples of how this works, see `Academy.User.changeset/2`.
  """
  def changeset(model, params \\ %{}) do
    model
    |> cast(params, @fields)
    |> validate_required(@required_fields)
    |> validate_length(:description, min: 10, max: 50)
    |> assoc_constraint(:category)
  end
end

web/controllers/api/skill_controller.ex
defmodule Academy.API.SkillController do
  @moduledoc ~S"""
  Controller for API skill related routes
  """

  use Academy.Web, :controller

  alias Academy.Repo

  alias Academy.Skill

  def index(conn, _params) do
    render conn, skills: Skill |> Repo.all |> Repo.preload(:category)
  end

  def show(conn, %{"id" => id}) do
    render conn, skill: Skill |> Repo.get(id) |> Repo.preload(:category)
  end

end

web/controllers/skill_controller.ex
defmodule Academy.SkillController do
  @moduledoc ~S"""
  The skill controller
  """

  use Academy.Web, :controller

  alias Academy.Repo
  alias Academy.Skill
  alias Academy.SkillCategory

  plug Guardian.Plug.EnsureAuthenticated, [handler: __MODULE__]

  def index(conn, _params) do
    skills = Repo.all(Skill) |> Repo.preload(:category)
    render conn, "index.html", skills: skills
  end

  def edit(conn, %{"id" => skill_id}) do
    categories = SkillCategory
                  |> Repo.all
                  |> Enum.map(fn category -> {category.name, category.id} end)
    skill = Repo.get!(Skill, skill_id) |> Repo.preload(:category)
    render conn, "edit.html", skill: skill, changeset: Skill.changeset(skill), categories: categories
  end

  def update(conn, %{"id" => skill_id, "skill" => skill_params}) do
    skill = Skill
            |> Repo.get!(skill_id)
            |> Repo.preload(:category)

    changeset = build_skill_changeset(skill, skill_params)

    case Repo.update(changeset) do
      {:ok, _skill} ->
        conn
        |> put_flash(:info, "Skill updated successfully.")
        |> redirect(to: skill_path(conn, :index))
      {:error, changeset} ->
        categories = SkillCategory
                      |> Repo.all
                      |> Enum.map(fn category -> {category.name, category.id} end)
        render conn, "edit.html", skill: skill, changeset: changeset, categories: categories
    end
  end

  def new(conn, _params) do
    categories = SkillCategory
                  |> Repo.all
                  |> Enum.map(fn category -> {category.name, category.id} end)
    changeset = Skill.changeset(%Skill{})
    render conn, "new.html", changeset: changeset, categories: categories
  end

  def create(conn, %{"skill" => skill_params}) do
    changeset = build_skill_changeset(%Skill{}, skill_params)
    case Repo.insert(changeset) do
      {:ok, _skill} ->
        conn
        |> put_flash(:info, "Skill successfully created")
        |> redirect(to: skill_path(conn, :index))
      {:error, changeset} ->
        categories = SkillCategory
                      |> Repo.all
                      |> Enum.map(fn category -> {category.name, category.id} end)
        render conn, "new.html", changeset: changeset, categories: categories
    end
  end

  defp build_skill_changeset(skill, skill_params) do
    changeset = skill
                |> Skill.changeset(skill_params)

    case skill_params["category_id"] do
      "" -> Ecto.Changeset.put_assoc(changeset, :category, nil)
      _  ->
        category_changeset = SkillCategory
                              |> Repo.get!(skill_params["category_id"])
                              |> SkillCategory.changeset
        Ecto.Changeset.put_assoc(changeset, :category, category_changeset)
    end

  end

  def delete(conn, %{"id" => skill_id}) do
    Skill
    |> Repo.get!(skill_id)
    |> Repo.delete!

    conn
    |> put_flash(:info, "Skill successfully deleted")
    |> redirect(to: skill_path(conn, :index))
  end

  @doc ~S"""
  Function called if the user is not authenticated and tried to view a page
  requiring authentication
  """
  def unauthenticated(conn, _params) do
    conn
    |> put_status(401)
    |> render(Academy.ErrorView, :"401")
  end

end

web/views/skill_view.ex
defmodule Academy.SkillView do
  @moduledoc ~S"""
  Module used to render skill related pages (e.g. Available skills page).
  """

  use Academy.Web, :view

  alias Academy.SkillCategoryView

  @doc ~S"""
  Get the category name of the given skill, or "No category" if it doesn't have
  one.
  """
  def category_name(skill) do
    SkillCategoryView.name(skill.category)
  end

end

web/templates/skill/category_header.html.eex
<header>
  <h2 class="category-name"><%= SkillCategoryView.name(@category) %></h2>
  <%= if @category do %>
    <div class="edit-buttons">
      <%= link "✎", to: skill_category_path(@conn, :edit, @category.id),
                    class: "tooltip",
                    data: [tooltip: "Edit category"] %>
      <%= link "✗", to: skill_category_path(@conn, :delete, @category.id),
                    method: :delete,
                    class: "tooltip",
                    data: [
                      tooltip: "Delete category",
                      confirm: "Are you sure you want to delete the #{@category.name} category?"] %>
    </div>
  <% end %>
</header>

web/templates/skill/edit.html.eex
<section class="skill-edit form">
  <h1>Skill edit: <%= @skill.name %></h1>

  <%= render "form.html", changeset: @changeset, 
                          categories: @categories,
                          action: skill_path(@conn, :update, @skill.id),
                          submit_text: "Change skill" %>
</section>

<script>
  window.features = {
    "forms": {}
  }
</script>

web/templates/skill/form.html.eex
<%= form_for @changeset, @action, fn f -> %>

  <%= input_group f, :name do %>
    <%= text_input f, :name, required: "" %>
    <%= label f, :name, class: "text-input" %>
    <%= error_tag f, :name %>
  <% end %>

  <%= input_group f, :description do %>
    <%= text_input f, :description, required: "", minlength: "10", maxlength: "50" %>
    <%= label f, :description, class: "text-input" %>
    <%= error_tag f, :description %>
  <% end %>

  <%= input_group f, :category_id do %>
    <%= label f, :category_id %>
    <%= select f, :category_id, [{"No category", ""} | @categories] %>
    <%= error_tag f, :category_id %>
  <% end %>

  <%= submit @submit_text %>

<% end %>

web/templates/skill/index.html.eex
<section class="skills-edit">
  <h1>Available skills</h1>

  <div class="buttons">
    <%= button "Edit my skills", to: skill_level_path(@conn, :edit), method: :get %>
    <%= button "Create a new skill", to: skill_path(@conn, :new), method: :get %>
    <%= button "Create a new category", to: skill_category_path(@conn, :new), method: :get %>
  </div>

  <div class="skills-dashboard">
    <%= for {category, skills} <-
          Enum.group_by(@skills, fn skill -> skill.category end) do %>
      <div class="skill-category">
        <%= render "category_header.html", conn: @conn, category: category %>
        <table class="skills">
          <%= for skill <- skills do %>
            <tr>
              <td class="name"><%= skill.name %></td>
              <td class="description"><%= skill.description %></td>
              <td class="edit-button">
                <%= link "✎",
                      to: skill_path(@conn, :edit, skill.id),
                      class: "tooltip",
                      data: [tooltip: "Edit skill"]
                %>
              </td>
              <td class="delete-button">
                <%= link "✗",
                      to: skill_path(@conn, :delete, skill.id), method: :delete,
                      class: "tooltip",
                      data: [tooltip: "Delete skill",
                       confirm: "Are you sure you want to delete the #{skill.name} skill?"]
                %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    <% end %>
  </div>

</section>

web/templates/skill/new.html.eex
<section class="new-skill form">
  <h1>New skill</h1>

  <%= render "form.html", changeset: @changeset,
                          categories: @categories,
                          action: skill_path(@conn, :create),
                          submit_text: "Create skill" %>
</section>

<script>
  window.features = {
    "forms": {}
  }
</script>