web/router.ex
defmodule Academy.Router do
  use Academy.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers,
      %{"Content-Security-Policy"
       => ~S(
          default-src 'none';
          script-src 'self' 'unsafe-inline';
          connect-src 'self';
          img-src 'self';
          font-src 'self';
          style-src 'self';
        )}
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Academy do
    pipe_through [:browser, :browser_auth]

    get "/",      UserController, :index
    get "/about", PageController, :about

    get  "/login", SessionController, :new
    post "/login", SessionController, :create

    get "/logout", SessionController, :delete

    resources "/users", UserController, only: [:index, :show]

    get      "/account",      UserController, :show_self
    get      "/account/edit", UserController, :edit
    patch    "/account/edit", UserController, :update
    put      "/account/edit", UserController, :update
    delete   "/account/edit", UserController, :delete

    get  "/account/skills/edit", SkillLevelController, :edit
    post "/account/skills",      SkillLevelController, :update

    resources "/skills",          SkillController, except: [:show, :update, :create]
    post      "/skills/new",      SkillController, :create
    patch     "/skills/:id/edit", SkillController, :update
    put       "/skills/:id/edit", SkillController, :update

    resources "/skill_categories",          SkillCategoryController, only: [:edit, :new, :delete]
    post      "/skill_categories/new",      SkillCategoryController, :create
    patch     "/skill_categories/:id/edit", SkillCategoryController, :update
    put       "/skill_categories/:id/edit", SkillCategoryController, :update

    get  "/mail/:user", MailController, :new
    post "/mail/:user", MailController, :send
  end

  scope "/api", Academy do
    pipe_through :api

    resources "/users", API.UserController, only: [:index, :show]

    resources "/skills", API.SkillController, only: [:index, :show]

    resources "/skill_categories", API.SkillCategoryController, only: [:index, :show]
  end
end

web/models/user.ex
defmodule Academy.User do
  @moduledoc ~S"""
  Defines a user model.

  Composition
  -----------

  A user is composed of a name, a biography, his availability and his avatar
  (handled by the `Academy.Avatar` module).

  A user also has a number of skill levels, which are defined in the
  `Academy.SkillLevel` module.

  You can also get his bare skills (without their levels) and his skill
  categories (without the skills)

  Getting the associations
  ------------------------

  In order to get his skill levels, skills or skill categories, one must use the
  `Academy.Repo.Preload/1` function like so:

      alias Academy.Repo
      alias Academy.User

      # Will get the user and his skill levels (but not his skills, so you
      # won't have their name)
      Repo.get(User, id) |> Repo.preload(:skill_levels)

      # Will get the user and his skill levels and skills
      Repo.get(User, id) |> Repo.preload(:skills)

      # Will get the user and his skill levels, skills and skill categories
      Repo.get(User, id) |> Repo.preload(:skill_categories)
  """

  use Academy.Web, :model

  use Arc.Ecto.Schema

  schema "users" do
    field :name, :string
    field :bio, :string
    field :available, :boolean
    field :avatar, Academy.Avatar.Type
    field :email, :string
    field :show_email, :boolean, default: false
    field :github_username, :string

    has_many :skill_levels, Academy.SkillLevel
    has_many :skills, through: [:skill_levels, :skill]
    has_many :skill_categories, through: [:skills, :category]

    timestamps
  end

  @required_fields ~w(name show_email)a
  @optional_fields ~w(bio available email github_username)a
  @fields @required_fields ++ @optional_fields

  @doc ~S"""
  Creates a changeset based on the `model` and `params`.

  Examples:

      alias Academy.User
      alias Academy.Repo

      # Create a new user with name "guest" and insert it in the database
      User.changeset(%User{}, name: "guest")
      |> Repo.insert!

      # Rename a user
      Repo.get_by(User, name: "guest")
      |> User.changeset(name: "guest1")
      |> Repo.update!
  """
  def changeset(model, params \\ %{}) do
    model
    |> cast(params, @fields)
    |> validate_required(@required_fields)
    |> cast_attachments(params, [:avatar])
    |> validate_length(:bio, min: 10, max: 140)
    |> validate_email(:email)
    |> validate_github_username(:github_username)
    #|> validate_avatar(params)
  end

  def validate_email(changeset, field) do
    email = get_field(changeset, field)
    if email !== nil do
      validate_format(changeset,
       :email, ~r/\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i)
    else
      changeset
    end
  end

  @doc ~S"""
  Validate a github username in a changeset.
  """
  def validate_github_username(changeset, field) do
    username = get_field(changeset, field)
    if username !== nil do

      valid? = case String.length username do
        0 -> false
        1 -> Regex.match?(~r/^[[:alnum:]]+$/, username)
        2 -> Regex.match?(~r/^[[:alnum:]]+$/, username)
        _ -> Regex.match?(~r/^[[:alnum:]][[:alnum:]-]+[[:alnum:]]$/, username) and
          not String.contains?(username, "--")
      end

      if valid? do
        changeset
      else
        add_error(changeset, field, "does not look like a Github username")
      end

    else
      changeset
    end
  end

  @doc ~S"""
  Validate an avatar

  Currently not working.
  """
  def validate_avatar(changeset, params) do
    # TODO: validate the size/space usage of the image
    changeset
  end

end

web/controllers/api/user_controller.ex
defmodule Academy.API.UserController do
  @moduledoc ~S"""
  Controller for API user related routes
  """

  use Academy.Web, :controller

  alias Academy.Repo

  alias Academy.User
  alias Academy.Avatar

  @doc ~S"""
  Show all users
  """
  def index(conn, _params) do
    render conn, users: User |> Repo.all |> Repo.preload(skills: :category)
  end

  def show(conn, %{"id" => id}) do
    render conn, user: User |> Repo.get(id) |> Repo.preload(skills: :category)
  end

end

web/controllers/user_controller.ex
defmodule Academy.UserController do
  @moduledoc ~S"""
  Controller for user related routes
  """

  use Academy.Web, :controller

  alias Academy.Repo

  alias Academy.User
  alias Academy.Avatar

  alias Academy.SessionController

  require Logger

  plug Guardian.Plug.EnsureAuthenticated, [handler: __MODULE__] when not action in [:show, :index]
  plug :scrub_params, "user" when action in [:update]

  @doc ~S"""
  Show all users (front page)
  """
  def index(conn, _params) do
    render conn, "all.html", users: User |> Repo.all |> Repo.preload(:skills)
  end

  def edit(conn, _params) do
    current_user = SessionController.current_user(conn)
    render conn, "edit.html", user: current_user, changeset: User.changeset(current_user)
  end

  def show(conn, %{"id" => username}) do
    case Repo.get_by(User, name: username) do
      nil -> conn
             |> put_status(404)
             |> render(Academy.ErrorView, :"404")
      user -> render conn, "full-card.html", user: user |> Repo.preload([skills: :category])
    end
  end

  @doc ~S"""
  Show the full card of the current user.

  This is actually a redirection to show with the good `id`
  """
  def show_self(conn, _params) do
    user = SessionController.current_user(conn)
    redirect(conn, to: user_path(conn, :show, user.name))
  end

  def update(conn, %{"user" => user_params}) do
    user_params = Map.update!(user_params, "bio", fn value ->
      case value do
        "" -> nil
        _  -> value
      end
    end)

    user = SessionController.current_user(conn)
    changeset = User.changeset(user, user_params)

    case Repo.update(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user.name))
      {:error, changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn) do

  end

  @doc ~S"""
  Get a user by name, creating it if he does not exists
  """
  def get_or_create(username) do
    case Repo.get_by(User, name: username) do
      nil -> create(username)
      user -> user
    end
  end

  defp create(username) do
    Logger.info("Creating user #{username} in database")
    user = Repo.insert! User.changeset(%User{name: username}, %{})
    generated_avatar = AlchemicAvatar.generate(String.capitalize(user.name), 100)
    Avatar.store {generated_avatar, user}
    user
  end

  @doc ~S"""
  Function called if the user is not authenticated and tried to view a page
  requiring authentication
  """
  def unauthenticated(conn, _params) do
    conn
    |> put_status(401)
    |> render(Academy.ErrorView, :"401")
  end

end

web/views/user_view.ex
defmodule Academy.UserView do
  @moduledoc ~S"""
  Module used to render user related pages.
  """

  use Academy.Web, :view

  alias Academy.SessionController
  alias Academy.Avatar
  alias Academy.SkillView

  use Phoenix.HTML

  @doc ~S"""
  Rank the given list of users according to the sum of their skill levels.
  """
  def rank_users(users) do
    users
    |> Enum.group_by(&sum_skill_levels/1)
    |> Enum.sort(fn {lrank, _lusers}, {rrank, _rusers} -> lrank > rrank end)
    |> Enum.flat_map(fn {_rank, users} -> users end)
  end

  defp sum_skill_levels(user) do
    user.skill_levels
    |> Enum.map(fn skill_level -> skill_level.level end)
    |> Enum.sum
  end

  @doc ~S"""
  Generate the HTML of the inside of the full member card
  """
  def full_ratings(skill_levels) do
    skill_levels
    |> Enum.group_by(fn skill_level -> SkillView.category_name(skill_level.skill) end)
    |> Enum.map(fn {category_name, skill_levels} ->
      skill_levels = Enum.sort(skill_levels, &(&1.level > &2.level))
      content_tag :div,
        [content_tag(:h2, category_name), rating_table(skill_levels)],
        class: "category"
    end)
  end

  @doc ~S"""
  Generate the HTML of the inside of the small member card
  """
  def small_ratings(skill_levels) do
    skill_length = length(skill_levels)
    if skill_length > 4 do
      split_size = round(Float.ceil(skill_length / 2))
      skill_levels
      |> Enum.chunk(split_size, split_size, [])
      |> Enum.map(fn chunk ->
        chunk
        |> Enum.sort(&(&1.level > &2.level))
        |> Enum.take(5)
      end)
      |> Enum.map(&rating_table/1)
    else
      rating_table(skill_levels)
    end
  end

  @doc ~S"""
  Generate the HTML of a rating table

  Just the table of the association skill name / rating
  """
  def rating_table(skill_levels) do
    content_tag :table do
      Enum.map(skill_levels, fn skill_level ->
        content_tag :tr do
          [content_tag(:td, skill_level.skill.name, class: "skill-name tooltip",
            data: [tooltip: skill_level.skill.description]),
           content_tag(:td, rating(skill_level.level), class: "rating")]
        end
      end)
    end
  end

  @doc ~S"""
  Generate the stars for the given rating
  """
  def rating(level, max \\ 5, full_str \\ "★", empty_str \\ "☆") do
    String.duplicate(full_str, level) <> String.duplicate(empty_str, max - level)
  end

  @doc ~S"""
  Generate the HTML for the avatar picture of the current member.

  See `Academy.Avatar`
  """
  def avatar(user) do
    {:safe, "<img src=\"#{avatar_url user}\" alt=\"Profile picture\" class=\"profile-picture\">"}
  end

  @doc ~S"""
  Get the URI of the given user's avatar.
  """
  def avatar_url(user) do
    Avatar.url({user.avatar, user})
  end

  @doc ~S"""
  Generate the HTML of the availability icon for a member card
  """
  def availability_icon(true) do
    {:safe, "<div class=\"availability tooltip\" data-tooltip=\"Available\"><img src=\"/images/available.svg\" alt=\"Available\"></div>"}
  end

  def availability_icon(false) do
    {:safe, "<div class=\"availability tooltip\" data-tooltip=\"Unavailable\"><img src=\"/images/not-available.svg\" alt=\"Available\"></div>"}
  end

  def availability_icon(nil) do
    {:safe, "<div class=\"availability tooltip\" data-tooltip=\"Availability unknown\">?</div>"}
  end

  @doc ~S"""
  Generate the HTML for the full card's edit buttons

  This will return `nil` if the given username is not the current user's name.
  """
  def edit_buttons(conn, username) do
    user = SessionController.current_user(conn)
    if user do
      case user.name do
        ^username ->
          content_tag :div, [class: "edit-buttons"] do
            [link("✎",
              class: "edit-button tooltip",
              data: [tooltip: "Edit profile"],
              to: user_path(conn, :edit)),
            link("★",
              class: "edit-button tooltip",
              data: [tooltip: "Edit skills"],
              to: skill_level_path(conn, :edit))]
          end
        _ -> nil
      end
    end
  end

end

web/templates/user/all.html.eex
<div class="search">
  <label for="search-bar">🔎</label>
  <input type="search" placeholder="Search for a skill" id="search-bar">
</div>

<div class="member-card-grid">

  <%= for user <- rank_users(@users) do %>
    <%= render "small-card.html", conn: @conn, user: user %>
  <%= end %>

</div>

<script>
  window.features = {
    "front-search": {"search-bar-id": "search-bar"}
  }
</script>

web/templates/user/edit.html.eex
<section class="user-edit form">
  <h1>My account</h1>

  <%= if @changeset.action do %>
    <div class="alert alert-error">
      Oops, something went wrong! Please check the errors below.
    </div>
  <% end %>

  <%= form_for @changeset, user_path(@conn, :update), [multipart: true], fn f -> %>
    <%= input_group f, :available do %>
      <%= checkbox f, :available %>
      <%= label f, :available %>
      <%= error_tag f, :available %>
    <% end %>

    <%= input_group f, :bio do %>
      <%= label f, :bio %>
      <%= textarea f, :bio %>
      <%= error_tag f, :bio %>
    <% end %>

    <%= input_group f, :avatar do %>
      <%= label f, :avatar %>
      <%= file_input f, :avatar %>
      <%= error_tag f, :avatar %>
    <% end %>

    <%= input_group f, :github_username do %>
      <%= text_input f, :github_username %>
      <%= label f, :github_username, class: "text-input" %>
      <%= error_tag f, :github_username %>
    <% end %>

    <%= input_group f, :email do %>
      <%= text_input f, :email %>
      <%= label f, :email, class: "text-input" %>
      <%= error_tag f, :email %>
    <% end %>

    <%= input_group f, :show_email do %>
      <%= checkbox f, :show_email %>
      <%= label f, :show_email, "Display the email on your user page" %>
      <%= error_tag f, :show_email %>
    <% end %>

    <%= submit "Save changes" %>
  <% end %>
</section>

<script>
  window.features = {
    "forms": {}
  }
</script>

web/templates/user/full-card.html.eex
<section class="member-card full">
  <header>
    <%= avatar @user %>
    <h1><%= String.capitalize @user.name %></h1>
    <%= availability_icon(@user.available) %>
    <%= edit_buttons @conn, @user.name %>
  </header>
  <%= if @user.email !== nil or @user.github_username !== nil or @user.bio !== nil do %>
    <div class="user-info">
      <%= if @user.bio do %>
        <p class="bio">
          <%= @user.bio %>
        </p>
      <% end %>
      <ul class="social">
        <%= if @user.email do %>
          <%= if @user.show_email do %>
            <li>
              <a href="mailto:<%= @user.email %>">
                <img src="/images/mail-symbol.svg" alt="Mail symbol">
                <%= @user.email %>
              </a>
            </li>
          <%= else %>
            <li>
                <img src="/images/mail-symbol.svg" alt="Mail symbol">
                <%= link "Send an email", to: mail_path(@conn, :new, @user.name) %>
            </li>
          <% end %>
        <% end %>
        <%= if @user.github_username do %>
          <li>
            <a href="https://github.com/<%= @user.github_username %>">
              <img src="/images/github-mark.svg" alt="GitHub Mark">
              <%= @user.github_username %>
            </a>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="skills">
    <%= full_ratings @user.skill_levels %>
  </div>
</section>

web/templates/user/small-card.html.eex
<section class="member-card" id="member-<%= @user.id %>">
  <%= link to: user_path(@conn, :show, @user.name) do %>
    <header>
      <%= avatar @user %>
      <h1><%= String.capitalize @user.name %></h1>
      <%= availability_icon(@user.available) %>
    </header>
    <div class="skills">
      <table class="addendum"></table>
      <%= small_ratings @user.skill_levels %>
    </div>
  <% end %>
</section>