web/router.ex
defmodule Academy.Router do
  use Academy.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers,
      %{"Content-Security-Policy"
       => ~S(
          default-src 'none';
          script-src 'self' 'unsafe-inline';
          connect-src 'self';
          img-src 'self';
          font-src 'self';
          style-src 'self';
        )}
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Academy do
    pipe_through [:browser, :browser_auth]

    get "/",      UserController, :index
    get "/about", PageController, :about

    get  "/login", SessionController, :new
    post "/login", SessionController, :create

    get "/logout", SessionController, :delete

    resources "/users", UserController, only: [:index, :show]

    get      "/account",      UserController, :show_self
    get      "/account/edit", UserController, :edit
    patch    "/account/edit", UserController, :update
    put      "/account/edit", UserController, :update
    delete   "/account/edit", UserController, :delete

    get  "/account/skills/edit", SkillLevelController, :edit
    post "/account/skills",      SkillLevelController, :update

    resources "/skills",          SkillController, except: [:show, :update, :create]
    post      "/skills/new",      SkillController, :create
    patch     "/skills/:id/edit", SkillController, :update
    put       "/skills/:id/edit", SkillController, :update

    resources "/skill_categories",          SkillCategoryController, only: [:edit, :new, :delete]
    post      "/skill_categories/new",      SkillCategoryController, :create
    patch     "/skill_categories/:id/edit", SkillCategoryController, :update
    put       "/skill_categories/:id/edit", SkillCategoryController, :update

    get  "/mail/:user", MailController, :new
    post "/mail/:user", MailController, :send
  end

  scope "/api", Academy do
    pipe_through :api

    resources "/users", API.UserController, only: [:index, :show]

    resources "/skills", API.SkillController, only: [:index, :show]

    resources "/skill_categories", API.SkillCategoryController, only: [:index, :show]
  end
end

web/views/layout_view.ex
defmodule Academy.LayoutView do
  @moduledoc ~S"""
  Module used to render layout.
  """

  use Academy.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>*Nix Academy</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">


  <div class="wrapper">
    <header role="banner">
      <h1><%= link "*Nix Academy", to: user_path(@conn, :index) %></h1>

      <nav role="navigation">
        <ul>
          <li><%= link "About", to: page_path(@conn, :about) %></li>
          <%= if logged_in?(@conn) do %>
            <li><%= link "My account", to: user_path(@conn, :show_self) %></li>
            <li><%= link "Available skills", to: skill_path(@conn, :index) %></li>
            <li><%= link "Logout", to: session_path(@conn, :delete) %></li>
          <%= else %>
            <li><%= link "Login", to: session_path(@conn, :create) %></li>
          <% end %>
        </ul>
      </nav>
    </header>

    <div class="alert alert-error" role="alert"><%= get_flash(@conn, :error) %></div>
    <div class="alert alert-warn" role="alert"><%= get_flash(@conn, :warn) %></div>
    <div class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></div>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <footer>
      <ul>
        <li><a href="https://www.clubnix.fr/">clubnix.fr</a></li>
        <%#<li><a href="https://chat.clubnix.fr/">chat.clubnix.fr</a></li>%>
        <li><a href="https://git.clubnix.fr/">git.clubnix.fr</a></li>
        <%#<li><a href="https://docs.clubnix.fr/">docs.clubnix.fr</a></li>%>
      </ul>
      <ul>
        <li><a href="https://www.codecademy.com/">codecademy.com</a></li>
        <li><a href="http://exercism.io/">exercism.io</a></li>
        <li><a href="https://projecteuler.net/">projecteuler.net</a></li>
      </ul>
      <ul>
        <li><a href="http://web.archive.org/web/20160528105810/http://c.learncodethehardway.org/book/">c.learncodethehardway.org</a></li>
        <li><a href="http://learncpp.com/">learncpp.com</a></li>
        <li><a href="https://learnpythonthehardway.org/book/">learnpythonthehardway.org</a></li>
        <li><a href="http://elixir-lang.org/getting-started/introduction.html">elixir-lang.org</a></li>
      </ul>
      <ul>
        <li><a href="https://linuxjourney.com/">linuxjourney.com</a></li>
        <li><a href="https://overthewire.org/">overthewire.org</a></li>
      </ul>
    </footer>
  </div>

  <script
    defer
    src="<%= static_path(@conn, "/js/app.js") %>"
    onload="require('web/static/js/app').App.run()"></script>
</html>